
package org.tickets.bean;
// default package
// Generated 22-feb-2016 14:08:11 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer codigo;
	private String nombre;
	private Set subcategorias = new HashSet(0);

	public Categoria() {
	}

	public Categoria(String nombre) {
		this.nombre = nombre;
	}

	public Categoria(String nombre, Set subcategorias) {
		this.nombre = nombre;
		this.subcategorias = subcategorias;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getSubcategorias() {
		return this.subcategorias;
	}

	public void setSubcategorias(Set subcategorias) {
		this.subcategorias = subcategorias;
	}

}
