package org.tickets.bean;
// default package
// Generated 22-feb-2016 14:08:11 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "wewew")
@NamedQuery(name = "sds", query = "select e from Empleado e where e.nombres = :nombre")
public class Empleado implements java.io.Serializable {

	@Id
	private Byte codigo;
	private Perfil perfil;
	private String nombres;
	private String apellidos;
	private String email;
	private String clave;
	private char sexo;

	public Empleado() {
	}

	public Empleado(Perfil perfil, String nombres, String apellidos, String email, String clave, char sexo) {
		this.perfil = perfil;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.email = email;
		this.clave = clave;
		this.sexo = sexo;
	}

	public Byte getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Byte codigo) {
		this.codigo = codigo;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public char getSexo() {
		return this.sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

}
