package org.tickets.bean;
// default package
// Generated 22-feb-2016 14:08:11 by Hibernate Tools 4.3.1.Final

/**
 * Soliciones generated by hbm2java
 */
public class Soliciones implements java.io.Serializable {

	private Integer codigo;
	private Solicitud solicitud;
	private String solucion;

	public Soliciones() {
	}

	public Soliciones(Solicitud solicitud, String solucion) {
		this.solicitud = solicitud;
		this.solucion = solucion;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	public String getSolucion() {
		return this.solucion;
	}

	public void setSolucion(String solucion) {
		this.solucion = solucion;
	}

}
